// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpxNsggegzxBNZI8FOBvxkWpFbky-lGL0',
    appId: '1:554020027328:android:6ef5acdcea2537ca9f6625',
    messagingSenderId: '554020027328',
    projectId: 'omegaapp-dannylflutter',
    storageBucket: 'omegaapp-dannylflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM7jHwry1ypMT68BlWcsY-B1acpZS4lMo',
    appId: '1:554020027328:ios:211e5bbbab910d009f6625',
    messagingSenderId: '554020027328',
    projectId: 'omegaapp-dannylflutter',
    storageBucket: 'omegaapp-dannylflutter.appspot.com',
    iosClientId: '554020027328-aoql4mikcobkprgje7ag80nv138nbs5b.apps.googleusercontent.com',
    iosBundleId: 'se.dannyl.omegalogin',
  );
}
